"""empty message

Revision ID: 157970bef391
Revises: None
Create Date: 2016-04-04 16:22:51.528537

"""

# revision identifiers, used by Alembic.
revision = '157970bef391'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('comment', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'comment')
    ### end Alembic commands ###
